services:
    db:
        image: mysql:8.2
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
volumes:
    data: