services:
    db:
        image: mysql:8.2
        container_name: mysql-products
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: products
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql
            - ./docs/db/mysql/database.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    data: